FROM node:22-bookworm-slim
WORKDIR /app

# Sin telemetría
ENV NEXT_TELEMETRY_DISABLED=1

# npm ci para dependencias exactas del package-lock
COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 3000

CMD ["npm", "run", "dev"]
