export const projects = [
  {
    name: 'Mi Portafolio',
    description:
      'Portafolio web personal desarrollado con Next.js para presentar proyectos y habilidades, con diseño responsivo, animaciones y enfoque en experiencia de usuario.',
    toolsUsed: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer motion'],
    linkDeploy: 'https://personal-portfolio-vera-daniel.vercel.app/#projects',
    linkGitHubBackend: 'No disponible',
    linkGitHubFrontend: 'https://github.com/DanielVeraOrtiz/personal-portfolio',
    imagesComputer: [
      '/Mipagina/computer/hero.png',
      '/Mipagina/computer/about.png',
      '/Mipagina/computer/skill.png',
      '/Mipagina/computer/skillTools.png',
      '/Mipagina/computer/project.png',
      '/Mipagina/computer/projectmodal.png',
      '/Mipagina/computer/projectmodalex.png',
      '/Mipagina/computer/contact.png',
      '/Mipagina/computer/herolight.png',
      '/Mipagina/computer/skillToolslight.png',
    ],
    imagesPhone: [
      '/Mipagina/mobil/hero.png',
      '/Mipagina/mobil/heronavbar.png',
      '/Mipagina/mobil/about.png',
      '/Mipagina/mobil/skill.png',
      '/Mipagina/mobil/skillTools.png',
      '/Mipagina/mobil/project.png',
      '/Mipagina/mobil/projectmodal.png',
      '/Mipagina/mobil/contact.png',
      '/Mipagina/mobil/footer.png',
    ],
    imagesTablet: [
      '/Mipagina/tablet/hero.png',
      '/Mipagina/tablet/heronavbar.png',
      '/Mipagina/tablet/about.png',
      '/Mipagina/tablet/skill.png',
      '/Mipagina/tablet/skillTools.png',
      '/Mipagina/tablet/project.png',
      '/Mipagina/tablet/projectmodal.png',
      '/Mipagina/tablet/contact.png',
    ],
  },
  {
    name: 'Pyng Games',
    description:
      'Proyecto web personal de juegos con autenticación JWT, backend propio y gestión de favoritos, incluyendo testing automatizado (unitario, integración y E2E) y diseño responsivo.',
    toolsUsed: [
      'React',
      'Javascript',
      'Jest',
      'Supertest',
      'Playwright',
      'Node.js',
      'PostgreSQL',
      'Sequelize',
      'Koa',
    ],
    linkDeploy: 'No disponible',
    linkGitHubBackend: 'https://github.com/DanielVeraOrtiz/classic_games_page_backend',
    linkGitHubFrontend: 'https://github.com/DanielVeraOrtiz/classic_games_page',
    imagesComputer: [
      '/ClassicGamePage/computer/landing.png',
      '/ClassicGamePage/computer/landinglogin.png',
      '/ClassicGamePage/computer/landingsignup.png',
      '/ClassicGamePage/computer/landinglogueado.png',
      '/ClassicGamePage/computer/gamepage.png',
      '/ClassicGamePage/computer/gamepagesidebar.png',
      '/ClassicGamePage/computer/gamepageexpandedv2.png',
      '/ClassicGamePage/computer/landinglight.png',
      '/ClassicGamePage/computer/gamepagelight.png',
    ],
    imagesPhone: [
      '/ClassicGamePage/mobil/landing.png',
      '/ClassicGamePage/mobil/landingsidebar.png',
      '/ClassicGamePage/mobil/landinglogin.png',
      '/ClassicGamePage/mobil/landingsignup.png',
      '/ClassicGamePage/mobil/gamepage.png',
      '/ClassicGamePage/mobil/gamepagesidebar.png',
      '/ClassicGamePage/mobil/gamepageexpanded.png',
    ],
    imagesTablet: [
      '/ClassicGamePage/tablet/landing.png',
      '/ClassicGamePage/tablet/landingsidebar.png',
      '/ClassicGamePage/tablet/landinglogin.png',
      '/ClassicGamePage/tablet/landingsignup.png',
      '/ClassicGamePage/tablet/gamepage.png',
      '/ClassicGamePage/tablet/gamepagesidebar.png',
      '/ClassicGamePage/tablet/gamepageexpanded.png',
    ],
  },
  {
    name: 'Mascotalerta HT',
    description:
      'Proyecto universitario en equipo de 5 personas para Mascotalerta, enfocado en la gestión de animales perdidos, robados y encontrados, junto con hogares temporales. Incluye autenticación, roles y un sistema de IA para detectar similitudes entre reportes.',
    toolsUsed: [
      'React',
      'JavaScript',
      'Node.js',
      'PostgreSQL',
      'Sequelize',
      'Koa',
      'Mui',
      'FastAPI',
      'DINOv2',
      'HuggingFace',
      'Cloudinary',
      'Auth0',
    ],
    linkDeploy: 'No disponible',
    linkGitHubBackend: 'No disponible',
    linkGitHubFrontend: 'No disponible',
    imagesComputer: [
      '/Mascotalerta/computer/landingsola.png',
      '/Mascotalerta/computer/landing.png',
      '/Mascotalerta/computer/formulario.png',
      '/Mascotalerta/computer/listacasos.png',
      '/Mascotalerta/computer/caso.png',
      '/Mascotalerta/computer/serhogartemporal.png',
      '/Mascotalerta/computer/perfil.png',
      '/Mascotalerta/computer/preguntas.png',
      '/Mascotalerta/computer/sobrenosotros.png',
    ],
    imagesPhone: [
      '/Mascotalerta/mobil/landing.png',
      '/Mascotalerta/mobil/formulario.png',
      '/Mascotalerta/mobil/listacasos.png',
      '/Mascotalerta/mobil/caso.png',
      '/Mascotalerta/mobil/serhogartemporal.png',
      '/Mascotalerta/mobil/perfil.png',
      '/Mascotalerta/mobil/preguntas.png',
      '/Mascotalerta/mobil/sobrenosotros.png',
    ],
    imagesTablet: [
      '/Mascotalerta/tablet/landing.png',
      '/Mascotalerta/tablet/formulario.png',
      '/Mascotalerta/tablet/listacasos.png',
      '/Mascotalerta/tablet/caso.png',
      '/Mascotalerta/tablet/serhogartemporal.png',
      '/Mascotalerta/tablet/perfil.png',
      '/Mascotalerta/tablet/preguntas.png',
      '/Mascotalerta/tablet/sobrenosotros.png',
    ],
  },
  {
    name: 'JDP Calendario',
    description:
      'Proyecto web universitario entre 3 personas tipo calendario para gestionar tareas y metas, con autenticación JWT, CRUD completo y seguimiento de progreso mediante una interfaz clara y moderna.',
    toolsUsed: ['React', 'JavaScript', 'Node.js', 'PostgreSQL', 'Sequelize', 'Koa', 'Bootstrap'],
    linkDeploy: 'No disponible',
    linkGitHubBackend: 'No disponible',
    linkGitHubFrontend: 'No disponible',
    imagesComputer: [
      '/JDP/computer/JDPlanding.png',
      '/JDP/computer/JDPcalendario.png',
      '/JDP/computer/JDPcalendarionew.png',
      '/JDP/computer/JDPmetas.png',
      '/JDP/computer/JDPcalendariolight.png',
      '/JDP/computer/JDPmetaslight.png',
    ],
    imagesPhone: [
      '/JDP/mobil/JDPlandingmobil.png',
      '/JDP/mobil/JDPlandingnavbarmobil.png',
      '/JDP/mobil/JDPcalendarionewmobil.png',
      '/JDP/mobil/JDPcalendarionewmobilv2.png',
      '/JDP/mobil/JDPmetasmobil.png',
    ],
    imagesTablet: [
      '/JDP/tablet/JPDlandingtablet.png',
      '/JDP/tablet/JDPlandingnavbartablet.png',
      '/JDP/tablet/JDPcalendariotablet.png',
      '/JDP/tablet/JPDcalendarionewtablet.png',
      '/JDP/tablet/JDPmetastablet.png',
    ],
  },
];
